# Generated by Django 5.0.6 on 2024-12-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('hours_of_operation', models.CharField(max_length=50)),
                ('working_days', models.CharField(max_length=50)),
            ],
        ),
    ]
