# Generated by Django 5.0.6 on 2024-12-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_business_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Enter a rating between 0 and 10', max_digits=3, null=True),
        ),
    ]
