# Generated by Django 5.0.6 on 2024-12-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_business_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='rating',
        ),
    ]
